const mongoose = require('mongoose');

const ProductosSchema = mongoose.Schema({
    img:{
        type:String,
        default:null
    },
    imagenes:{
        type:Array
    },
    nombre:{
        type:String
    },
    sku:{
        type:String
    },
    precio:{
        type:Number
    },
    precioVenta:{
        type:Number
    },
    descripcionProducto:{
        type:String
    },
    specs:{
        type:String
    },
    almacenes:{
        type:Array
    },
    peso:{
        type:Number
    },
    largo:{
        type:Number,
    },
    ancho:{
        type:Number
    },
    alto:{
        type:Number
    },
    colores:{
        type:Array,
        default:[]
    },
    imagenesColores:{
        type:Array,
        default:[]
    },
    categoria:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Categoria'
    },
    pdf:{
        type:String,
        default:null
    },
    accesorios:{
        type:Array
    },
    vinculados:{
        type:Array,
        default:[]
    },
    principal:{
        type:Boolean,
        default:false
    },
    descripcionCorta:{
        type:String
    }
})

module.exports = mongoose.model('Productos',ProductosSchema);